### ISSUE TITLE
Multiple authentication methods

### ISSUE THREAD

**Issue by schetle** [jpulgarin/django-tokenapi#23]
I have a server that has HTTP Auth for non-production purposes, but I want the presence of the "user" and "token" params to take precedence over HTTP Auth in token_required().

I will end up changing token_required temporarily for my needs, but my suggestion here is to allow the developer to specify a preferred method if both HTTP Auth and Token auth is present.

**Comment by jpulgarin** [comment]
Hey @schetle.

That make sense, I'll change the order we check things in so that user and token parameters take precedence.

**Comment by jpulgarin** [comment]
Closed with 4bcbb76409b391ee901198835675700747e6b554
