### ISSUE TITLE
TOKEN_TIMEOUT_DAYS

### ISSUE THREAD

**Issue by schetle** [jpulgarin/django-tokenapi#24]
My tokens seem to expire after a couple days, despite having this set to a much larger number in settings.py

I looked through the code, but didn't find any references to TOKEN_TIMEOUT_DAYS.

**Comment by jpulgarin** [comment]
Wow thanks for reporting this. Turns out we were looking at  `PASSWORD_RESET_TIMEOUT_DAYS` instead.
